routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Auth::routes();

Route::get('/', function () {
    return view('backend.dashboard.index');
})->middleware('auth');

Route::match(['get', 'post'], 'login', ['as' => 'login', 'uses' => 'Auth\LoginController@signin']);

// Route::match(['get', 'post'], '/signin   ', 'Auth\LoginController@signin');

Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware' => ['auth']], function () {
    //Login, ChangePassword, Setting Admin
    Route::get('/backend/dashboard', 'Backend\DashboardController@Index');
    Route::get('/auth/settings', 'Auth\LoginController@settings');
    Route::get('/auth/check-pwd', 'Auth\LoginController@chkPassword');
    Route::match(['get', 'post'], '/auth/update-password', 'Auth\LoginController@updatePassword');
    Route::match(['get', 'post'], '/signout', 'Auth\LoginController@Signout');

    Route::match(['get', 'post'], '/backend/working-days/data', 'Backend\WorkingDaysController@indexData');
    Route::resource('/backend/working-days', 'Backend\WorkingDaysController');

    Route::resource('/backend/admins', 'Backend\AdminsController');
    Route::resource('/backend/partners', 'Backend\PartnersController');
    Route::match(['get', 'post'], '/backend/senders/data', 'Backend\SendersController@indexData');
    Route::resource('/backend/senders', 'Backend\SendersController');

    Route::match(['get', 'post'], '/backend/products/data', 'Backend\ProductsController@indexData');
    Route::match(['get', 'post'], '/backend/products/details-data/{id}', 'Backend\ProductsController@indexDataDetail');
    Route::resource('/backend/products', 'Backend\ProductsController');
    Route::get('/backend/products/delete-image/{id}', 'Backend\ProductsController@deleteImage');
    Route::match(['get', 'post'], '/backend/products/add-attributes/{id}', 'Backend\ProductsController@addAttributes');
    Route::match(['get', 'post'], '/backend/products/delete-attribute/{id}', 'Backend\ProductsController@deleteAttribute');

    Route::match(['get', 'post'], '/backend/stocks/manage/update', 'Backend\StocksController@updateManage')->name('stocks.manage.update');
    Route::match(['get', 'post'], '/backend/stocks/manage/{id}', 'Backend\StocksController@manage')->name('stocks.manage');
    Route::resource('/backend/stocks', 'Backend\StocksController');

    Route::match(['get', 'post'], '/backend/orders/data', 'Backend\OrdersController@indexData');
    Route::resource('/backend/orders', 'Backend\OrdersController');

    Route::match(['get', 'post'], '/backend/claim-orders/data/{id}', 'Backend\ClaimOrdersController@showData');
    Route::match(['get', 'post'], '/backend/claim-orders/{id}/create/', 'Backend\ClaimOrdersController@create')->name('claim-orders.create');
    Route::resource('/backend/claim-orders', 'Backend\ClaimOrdersController')->only([
        'store', 'show', 'edit', 'update', 'destroy',
    ]);;

    /**
     * Print Orders
     */
    Route::match(['get', 'post'], '/backend/printorders/', 'Backend\PrintOrdersController@index');
    Route::match(['get', 'post'], '/backend/printorders/data', 'Backend\PrintOrdersController@indexData');

    Route::get('/backend/pdf/print-per-orders/{id}', 'Backend\PrintOrdersController@pdfPerOrder');
    Route::match(['get', 'post'], '/backend/pdf/print-selected-orders', 'Backend\PrintOrdersController@pdfselectedOrder')->name('print-selected-orders');

    /**
     * Print Claim Orders
     */
    Route::match(['get', 'post'], '/backend/printclaimorders/', 'Backend\PrintClaimOrdersController@index');
    Route::match(['get', 'post'], '/backend/printclaimorders/data', 'Backend\PrintClaimOrdersController@indexData');

    Route::get('/backend/pdf/printclaim-per-orders/{id}', 'Backend\PrintClaimOrdersController@pdfPerOrder');
    Route::match(['get', 'post'], '/backend/pdf/print-selected-claimorders', 'Backend\PrintClaimOrdersController@pdfselectedOrder')->name('print-selected-claimorders');

    // Route::resource('/backend/reportorders', 'Backend\ReportOrdersController');
    Route::match(['get', 'post'], '/backend/reportorders', 'Backend\ReportOrdersController@index')->name('reportorders.index');
    Route::match(['get', 'post'], '/backend/reportorders/data', 'Backend\ReportOrdersController@indexData')->name('reportorders.indexData');

    Route::match(['get', 'post'], '/backend/report-claimorders', 'Backend\ReportClaimOrdersController@index')->name('report-claimorders.index');
    Route::match(['get', 'post'], '/backend/report-claimorders/data', 'Backend\ReportClaimOrdersController@indexData')->name('report-claimorders.indexData');
});

app/Http/Controllers/Backend/AdminsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use Spatie\Permission\Models\Role;
use DB;
use Hash;


class AdminsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = User::orderBy('id', 'ASC')
            ->join('model_has_roles', 'users.id', '=', 'model_has_roles.model_id')
            ->where('role_id', '=', 1)
            ->whereNull('deleted_at')->paginate(50);
        return view('backend.admins.index', compact('data'))
            ->with('i', ($request->input('page', 1) - 1) * 50);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $roles = Role::pluck('name', 'name')->all();
        return view('backend.admins.create'/*, compact('roles')*/);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'username' => 'required|unique:users,username',
            'password' => 'required|same:confirm-password'
        ]);
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);


        $user = User::create($input);
        $user->assignRole(1);


        return redirect()->route('admins.index')
            ->with('success', 'User created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('backend.admins.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);

        return view('backend.admins.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'username' => 'required|unique:users,username,' . $id,
            'password' => 'same:confirm-password'
        ]);


        $input = $request->all();
        if (!empty($input['password'])) {
            $input['password'] = Hash::make($input['password']);
        } else {
            $input = array_except($input, array('password'));
        }


        $user = User::find($id);
        $user->update($input);


        return redirect()->route('admins.index')
            ->with('success', 'User updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('admins.index')
            ->with('success', 'User deleted successfully');
    }
}

app/Http/Controllers/Backend/ClaimOrdersController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\ClaimOrder;
use App\Order;
use DB;
use Datatables;

class ClaimOrdersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        return view('backend.claimorders.create', compact('id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $this->validate($request, [
            "claim_name" => "required",
            "name_surename" => "required",
            "tel" => "required|numeric|digits:10",
            "address" => "required",
            "provinces" => "required",
            "amphures" => "required",
            "districts" => "required",
            "zipcode" => "required",
            "total_price" => "required|regex:/^\d+(\.\d{1,2})?$/",
        ]);

        $data = $request->all();

        $order = new ClaimOrder();
        $order->order_id =          $data['order_id'];
        $order->claim_name =        $data['claim_name'];
        $order->description =       $data['description'];
        $order->name_surename =       $data['name_surename'];
        $order->tel =               $data['tel'];
        $order->address =           $data['address'];
        $order->provinces =         $data['provinces'];
        $order->amphures =          $data['amphures'];
        $order->districts =         $data['districts'];
        $order->zipcode =           $data['zipcode'];
        $order->total_price =       $data['total_price'];
        $order->created_user_id =   Auth::user()->id;

        $order->save();

        $order_id = $data['order_id'];

        return redirect()->route('claim-orders.show', [$order_id])
            ->with('success', 'Claim has been added Successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order_id = $id;
        $data = Order::join('products', 'products.id', '=', 'orders.product_id')
            ->join('products_attributes', 'products_attributes.id', '=', 'orders.products_attributes_id')
            ->select(
                'orders.id',
                DB::raw("DATE_FORMAT(orders.updated_at, '%d/%m/%Y') AS order_date"),
                DB::raw("DATE_FORMAT(orders.updated_at, '%H:%i:%s') AS order_time"),
                'orders.name_surename',
                'orders.tel',
                'orders.address',
                DB::raw("CONCAT(districts,' ', amphures,' ', provinces) AS districts"),
                'zipcode AS zip_code',
                DB::raw("CONCAT(products.product_name,' ', products_attributes.color) AS product"),
                'orders.payment',
                'orders.total_price',
                'orders.purchase_channel',
                'orders.profile',
                'orders.created_at',
                'orders.updated_at',
                'orders.deleted_at'
            )->orderBy('orders.id', 'DESC');
        $data = $data->where('orders.id', '=', $order_id)->first();
        return view('backend.claimorders.index', compact('order_id', 'data'));
    }

    public function showData($id)
    {

        $data = ClaimOrder::where('claim_orders.order_id', '=', $id)
            ->select(
                'claim_orders.id',
                DB::raw("DATE_FORMAT(claim_orders.updated_at, '%d/%m/%Y') AS order_date"),
                DB::raw("DATE_FORMAT(claim_orders.updated_at, '%H:%i:%s') AS order_time"),
                'claim_orders.claim_name',
                'claim_orders.description',
                'claim_orders.name_surename',
                'claim_orders.tel',
                'claim_orders.address',
                DB::raw("CONCAT(claim_orders.districts,' ', claim_orders.amphures,' ', claim_orders.provinces) AS districts"),
                'claim_orders.zipcode AS zip_code',
                'claim_orders.total_price'
            )
            ->orderBy('claim_orders.id', 'DESC');

        $data = $data->get();

        return Datatables::of($data)->make();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $claim = ClaimOrder::find($id);
        // dd($claim);
        return view('backend.claimorders.edit', compact('claim'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        $this->validate($request, [
            "claim_name" => "required",
            "name_surename" => "required",
            "tel" => "required|numeric|digits:10",
            "address" => "required",
            "provinces" => "required",
            "amphures" => "required",
            "districts" => "required",
            "zipcode" => "required",
            "total_price" => "required|regex:/^\d+(\.\d{1,2})?$/",
        ]);

        ClaimOrder::where(['id' => $id])
            ->update([
                'claim_name'    =>  $data['claim_name'],
                'description'   =>  $data['description'],
                'name_surename' =>  $data['name_surename'],
                'tel'           =>  $data['tel'],
                'address'       =>  $data['address'],
                'provinces'     =>  $data['provinces'],
                'amphures'      =>  $data['amphures'],
                'districts'     =>  $data['districts'],
                'zipcode'       =>  $data['zipcode'],
                'total_price'   =>  $data['total_price']
            ]);

        $order_id = $data['order_id'];

        return redirect()->route('claim-orders.show', [$order_id])
            ->with('success', 'Claim Updated Successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        /*if(session('adminSession')){
            //Perform all dashboard tasks.
        }else{
            return redirect('/admin')->with('flash_message_error','Please login to access');
        }*/
        return view('backend.dashboard.index');
    }
}

app/Http/Controllers/Backend/ReportClaimOrdersController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\ClaimOrder;
use DB;

class ReportClaimOrdersController extends Controller
{
    function index(Request $request)
    {
        return view('backend.reportclaimorders.index');
    }

    function indexData(Request $request)
    {

        DB::connection()->enableQueryLog();

        $user = Auth::user()->getRoleNames();

        $data = ClaimOrder::select(
            'claim_orders.id',
            DB::raw("DATE_FORMAT(claim_orders.updated_at, '%d/%m/%Y') AS order_date"),
            DB::raw("DATE_FORMAT(claim_orders.updated_at, '%H:%i:%s') AS order_time"),
            'claim_orders.claim_name',
            'claim_orders.description',
            'claim_orders.name_surename',
            'claim_orders.tel',
            'claim_orders.address',
            DB::raw("CONCAT(claim_orders.districts,' ', claim_orders.amphures,' ', claim_orders.provinces) AS districts"),
            'claim_orders.zipcode AS zip_code',
            'claim_orders.total_price'
        )
            ->orderBy('claim_orders.id', 'DESC');

        if ($user[0] != 'admin') {
            $data = $data->where('created_user_id', '=', Auth::user()->id);
        }

        if (!empty($request->from_date)) {
            $data = $data->whereBetween(DB::raw('DATE(orders.created_at)'), array($request->from_date, $request->to_date));
        }

        $data = $data->get();

        return datatables()->of($data)->make(true);
    }
}

resources/views/backend/stocks/add.blade.php
@extends('layouts.limitless.index')

@section('content')
<div class="row">
    <div class="col-md-6">
        @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        {!! Form::model($data, ['method' => 'PATCH','class'=>'form-horizontal','route' => ['stocks.update', $data->id]])
        !!}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h5 class="panel-title">เพิ่ม Stock<a class="heading-elements-toggle"><i class="icon-more"></i></a></h5>
                <div class="heading-elements">
                    <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
                </div>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <label class="col-lg-3 control-label">ชื่อสินค้า:</label>
                    <div class="col-lg-9">
                        <div class="form-control-static">{{$data->product_name}}</div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">สี:</label>
                    <div class="col-lg-9">
                        <div class="form-control-static">{{$data->color}}</div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">จำนวน Stock คงเหลือ:</label>
                    <div class="col-lg-9">
                        <div class="form-control-static">{{$data->stock}}</div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">จำนวน Stock ที่นำเข้า:</label>
                    <div class="col-lg-9">
                        <input class="form-control" type="number" name="stock_add">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">ราคาทุนของ Stock ที่นำเข้า:</label>
                    <div class="col-lg-9">
                        <input class="form-control" type="number" name="price_cost">
                    </div>
                </div>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Submit form <i
                            class="icon-arrow-right14 position-right"></i></button>
                </div>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
</div>
@endsection

resources/views/backend/stocks/manage.blade.php
@extends('layouts.limitless.index')
@section('content')
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h5 class="panel-title">ระบบจัดการ Stock <a class="heading-elements-toggle"><i class="icon-more"></i></a>
            </h5>
            <div class="heading-elements">
                <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
            </div>
        </div>
        <div class="panel-body">
            <fieldset class="content-group">
                <input type="hidden" name="product_id" value="{{$products_attributes->id}}">
                <div class="form-group">
                    <label class="control-label col-xs-1">ชื่อสินค้า :</label>
                    <label class="control-label col-xs-2">
                        {{$products_attributes->product_name}}
                        {{$products_attributes->color}}
                    </label>
                </div>
            </fieldset>
            <div class="table-responsive">
                <table class="table table-bordered table-xxs">
                    <thead>
                        <tr class="bg-grey-600">
                            <th class="col-lg-2">id</th>
                            <th class="col-lg-2">นำเข้าวันที่</th>
                            <th class="col-lg-2">จำนวนสินค้าที่เพิ่ม</th>
                            <th class="col-lg-2">จำนวนสินค้าคงเหลือ</th>
                            <th class="col-lg-2">ราคาทุน</th>
                            <th class=" col-lg-2 text-center">ปรับ Stock</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                        $product_name_old = '';
                        @endphp
                        @foreach ($data as $key => $product)
                        <tr>
                            <td class="text-center">{{$product->id}}</td>
                            <td class="text-center">{{$product->created_at}}</td>
                            <td class="text-right">{{$product->stock_add}}</td>
                            <td class="text-right">{{$product->stock_balance}}</td>
                            {{-- <td class="text-center">{{$product->price_cost}}</td> --}}
                            <td>
                                <a href="#" data-type="text" data-pk="{{$product->id}}" data-title="ปรับ Stock คงเหลือ"
                                    class="editable-price_cost editable-click">{{$product->price_cost}}</a>
                            </td>
                            <td>
                                <a href="#" data-type="text" data-pk="{{$product->id}}" data-title="ปรับ Stock คงเหลือ"
                                    class="editable-stock_balance editable-click">{{$product->stock_balance}}</a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
</div>
<script>
    $(function() {

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        // Editable
        // ------------------------------

        // Change defaults
        $.fn.editable.defaults.highlight = false;
        $.fn.editable.defaults.mode = 'popup';
        $.fn.editableform.template = '<form class="editableform">' +
            '<div class="control-group">' +
            '<div class="editable-input"></div> <div class="editable-buttons"></div>' +
            '<div class="editable-error-block"></div>' +
            '</div> ' +
            '</form>';
        $.fn.editableform.buttons =
            '<button type="submit" class="btn btn-info btn-icon editable-submit"><i class="icon-check"></i></button>' +
            '<button type="button" class="btn btn-default btn-icon editable-cancel"><i class="icon-x"></i></button>';


        // Initialize
        $('.editable-price_cost').editable({
            name: 'price_cost',
            url: '{{route("stocks.manage.update")}}',
            type: 'text',
            pk: 1,
            success: function(response, newValue) {
                if(response == ''){
                    swal({title: "Success", text: "ปรับ Stock เรียบร้อย! \nClick 'Ok' to refresh page.", type: "success"},
                            function(){
                                location.reload();
                            }
                        );
                }else{
                    swal({title: "Error!", text: response, type: "error"},
                            function(){
                                location.reload();
                            }
                        );
                }
            }
        });

        $('.editable-stock_balance').editable({
            name: 'stock_balance',
            url: '{{route("stocks.manage.update")}}',
            type: 'text',
            pk: 1,
            success: function(response, newValue) {
                if(response == ''){
                    swal({title: "Success", text: "ปรับ Stock เรียบร้อย! \nClick 'Ok' to refresh page.", type: "success"},
                            function(){
                                location.reload();
                            }
                        );
                }else{
                    swal({title: "Error!", text: response, type: "error"},
                            function(){
                                location.reload();
                            }
                        );
                }
            }
        });
    });

</script>

@endsection