routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Auth::routes();

Route::get('/', function () {
    return view('backend.dashboard.index');
})->middleware('auth');

Route::match(['get', 'post'], 'login', ['as' => 'login', 'uses' => 'Auth\LoginController@signin']);

// Route::match(['get', 'post'], '/signin   ', 'Auth\LoginController@signin');

Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware' => ['auth']], function () {
    //Login, ChangePassword, Setting Admin
    Route::get('/backend/dashboard', 'Backend\DashboardController@Index');
    Route::get('/auth/settings', 'Auth\LoginController@settings');
    Route::get('/auth/check-pwd', 'Auth\LoginController@chkPassword');
    Route::match(['get', 'post'], '/auth/update-password', 'Auth\LoginController@updatePassword');
    Route::match(['get', 'post'], '/signout', 'Auth\LoginController@Signout');

    Route::match(['get', 'post'], '/backend/working-days/data', 'Backend\WorkingDaysController@indexData');
    Route::resource('/backend/working-days', 'Backend\WorkingDaysController');

    Route::resource('/backend/admins', 'Backend\AdminsController');
    Route::resource('/backend/partners', 'Backend\PartnersController');
    Route::match(['get', 'post'], '/backend/senders/data', 'Backend\SendersController@indexData');
    Route::resource('/backend/senders', 'Backend\SendersController');

    Route::match(['get', 'post'], '/backend/products/data', 'Backend\ProductsController@indexData');
    Route::match(['get', 'post'], '/backend/products/details-data/{id}', 'Backend\ProductsController@indexDataDetail');
    Route::resource('/backend/products', 'Backend\ProductsController');
    Route::get('/backend/products/delete-image/{id}', 'Backend\ProductsController@deleteImage');
    Route::match(['get', 'post'], '/backend/products/add-attributes/{id}', 'Backend\ProductsController@addAttributes');
    Route::match(['get', 'post'], '/backend/products/delete-attribute/{id}', 'Backend\ProductsController@deleteAttribute');

    Route::match(['get', 'post'], '/backend/stocks/manage/update', 'Backend\StocksController@updateManage')->name('stocks.manage.update');
    Route::match(['get', 'post'], '/backend/stocks/manage/{id}', 'Backend\StocksController@manage')->name('stocks.manage');
    Route::resource('/backend/stocks', 'Backend\StocksController');

    Route::match(['get', 'post'], '/backend/orders/data', 'Backend\OrdersController@indexData');
    Route::resource('/backend/orders', 'Backend\OrdersController');

    Route::match(['get', 'post'], '/backend/claim-orders/data/{id}', 'Backend\ClaimOrdersController@showData');
    Route::match(['get', 'post'], '/backend/claim-orders/{id}/create/', 'Backend\ClaimOrdersController@create')->name('claim-orders.create');
    Route::resource('/backend/claim-orders', 'Backend\ClaimOrdersController')->only([
        'store', 'show', 'edit', 'update', 'destroy',
    ]);;

    /**
     * Print Orders
     */
    Route::match(['get', 'post'], '/backend/printorders/', 'Backend\PrintOrdersController@index');
    Route::match(['get', 'post'], '/backend/printorders/data', 'Backend\PrintOrdersController@indexData');

    Route::get('/backend/pdf/print-per-orders/{id}', 'Backend\PrintOrdersController@pdfPerOrder');
    Route::match(['get', 'post'], '/backend/pdf/print-selected-orders', 'Backend\PrintOrdersController@pdfselectedOrder')->name('print-selected-orders');

    /**
     * Print Claim Orders
     */
    Route::match(['get', 'post'], '/backend/printclaimorders/', 'Backend\PrintClaimOrdersController@index');
    Route::match(['get', 'post'], '/backend/printclaimorders/data', 'Backend\PrintClaimOrdersController@indexData');

    Route::get('/backend/pdf/printclaim-per-orders/{id}', 'Backend\PrintClaimOrdersController@pdfPerOrder');
    Route::match(['get', 'post'], '/backend/pdf/print-selected-claimorders', 'Backend\PrintClaimOrdersController@pdfselectedOrder')->name('print-selected-claimorders');

    // Route::resource('/backend/reportorders', 'Backend\ReportOrdersController');
    Route::match(['get', 'post'], '/backend/reportorders', 'Backend\ReportOrdersController@index')->name('reportorders.index');
    Route::match(['get', 'post'], '/backend/reportorders/data', 'Backend\ReportOrdersController@indexData')->name('reportorders.indexData');

    Route::match(['get', 'post'], '/backend/report-claimorders', 'Backend\ReportClaimOrdersController@index')->name('report-claimorders.index');
    Route::match(['get', 'post'], '/backend/report-claimorders/data', 'Backend\ReportClaimOrdersController@indexData')->name('report-claimorders.indexData');
});

app/Http/Controllers/Backend/AdminsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use Spatie\Permission\Models\Role;
use DB;
use Hash;


class AdminsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = User::orderBy('id', 'ASC')
            ->join('model_has_roles', 'users.id', '=', 'model_has_roles.model_id')
            ->where('role_id', '=', 1)
            ->whereNull('deleted_at')->paginate(50);
        return view('backend.admins.index', compact('data'))
            ->with('i', ($request->input('page', 1) - 1) * 50);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $roles = Role::pluck('name', 'name')->all();
        return view('backend.admins.create'/*, compact('roles')*/);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'username' => 'required|unique:users,username',
            'password' => 'required|same:confirm-password'
        ]);
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);


        $user = User::create($input);
        $user->assignRole(1);


        return redirect()->route('admins.index')
            ->with('success', 'User created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('backend.admins.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);

        return view('backend.admins.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'username' => 'required|unique:users,username,' . $id,
            'password' => 'same:confirm-password'
        ]);


        $input = $request->all();
        if (!empty($input['password'])) {
            $input['password'] = Hash::make($input['password']);
        } else {
            $input = array_except($input, array('password'));
        }


        $user = User::find($id);
        $user->update($input);


        return redirect()->route('admins.index')
            ->with('success', 'User updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('admins.index')
            ->with('success', 'User deleted successfully');
    }
}

app/Http/Controllers/Backend/ClaimOrdersController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\ClaimOrder;
use App\Order;
use DB;
use Datatables;

class ClaimOrdersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        return view('backend.claimorders.create', compact('id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $this->validate($request, [
            "claim_name" => "required",
            "name_surename" => "required",
            "tel" => "required|numeric|digits:10",
            "address" => "required",
            "provinces" => "required",
            "amphures" => "required",
            "districts" => "required",
            "zipcode" => "required",
            "total_price" => "required|regex:/^\d+(\.\d{1,2})?$/",
        ]);

        $data = $request->all();

        $order = new ClaimOrder();
        $order->order_id =          $data['order_id'];
        $order->claim_name =        $data['claim_name'];
        $order->description =       $data['description'];
        $order->name_surename =       $data['name_surename'];
        $order->tel =               $data['tel'];
        $order->address =           $data['address'];
        $order->provinces =         $data['provinces'];
        $order->amphures =          $data['amphures'];
        $order->districts =         $data['districts'];
        $order->zipcode =           $data['zipcode'];
        $order->total_price =       $data['total_price'];
        $order->created_user_id =   Auth::user()->id;

        $order->save();

        $order_id = $data['order_id'];

        return redirect()->route('claim-orders.show', [$order_id])
            ->with('success', 'Claim has been added Successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order_id = $id;
        $data = Order::join('products', 'products.id', '=', 'orders.product_id')
            ->join('products_attributes', 'products_attributes.id', '=', 'orders.products_attributes_id')
            ->select(
                'orders.id',
                DB::raw("DATE_FORMAT(orders.updated_at, '%d/%m/%Y') AS order_date"),
                DB::raw("DATE_FORMAT(orders.updated_at, '%H:%i:%s') AS order_time"),
                'orders.name_surename',
                'orders.tel',
                'orders.address',
                DB::raw("CONCAT(districts,' ', amphures,' ', provinces) AS districts"),
                'zipcode AS zip_code',
                DB::raw("CONCAT(products.product_name,' ', products_attributes.color) AS product"),
                'orders.payment',
                'orders.total_price',
                'orders.purchase_channel',
                'orders.profile',
                'orders.created_at',
                'orders.updated_at',
                'orders.deleted_at'
            )->orderBy('orders.id', 'DESC');
        $data = $data->where('orders.id', '=', $order_id)->first();
        return view('backend.claimorders.index', compact('order_id', 'data'));
    }

    public function showData($id)
    {

        $data = ClaimOrder::where('claim_orders.order_id', '=', $id)
            ->select(
                'claim_orders.id',
                DB::raw("DATE_FORMAT(claim_orders.updated_at, '%d/%m/%Y') AS order_date"),
                DB::raw("DATE_FORMAT(claim_orders.updated_at, '%H:%i:%s') AS order_time"),
                'claim_orders.claim_name',
                'claim_orders.description',
                'claim_orders.name_surename',
                'claim_orders.tel',
                'claim_orders.address',
                DB::raw("CONCAT(claim_orders.districts,' ', claim_orders.amphures,' ', claim_orders.provinces) AS districts"),
                'claim_orders.zipcode AS zip_code',
                'claim_orders.total_price'
            )
            ->orderBy('claim_orders.id', 'DESC');

        $data = $data->get();

        return Datatables::of($data)->make();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $claim = ClaimOrder::find($id);
        // dd($claim);
        return view('backend.claimorders.edit', compact('claim'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        $this->validate($request, [
            "claim_name" => "required",
            "name_surename" => "required",
            "tel" => "required|numeric|digits:10",
            "address" => "required",
            "provinces" => "required",
            "amphures" => "required",
            "districts" => "required",
            "zipcode" => "required",
            "total_price" => "required|regex:/^\d+(\.\d{1,2})?$/",
        ]);

        ClaimOrder::where(['id' => $id])
            ->update([
                'claim_name'    =>  $data['claim_name'],
                'description'   =>  $data['description'],
                'name_surename' =>  $data['name_surename'],
                'tel'           =>  $data['tel'],
                'address'       =>  $data['address'],
                'provinces'     =>  $data['provinces'],
                'amphures'      =>  $data['amphures'],
                'districts'     =>  $data['districts'],
                'zipcode'       =>  $data['zipcode'],
                'total_price'   =>  $data['total_price']
            ]);

        $order_id = $data['order_id'];

        return redirect()->route('claim-orders.show', [$order_id])
            ->with('success', 'Claim Updated Successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        /*if(session('adminSession')){
            //Perform all dashboard tasks.
        }else{
            return redirect('/admin')->with('flash_message_error','Please login to access');
        }*/
        return view('backend.dashboard.index');
    }
}

app/Http/Controllers/Backend/ReportClaimOrdersController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\ClaimOrder;
use DB;

class ReportClaimOrdersController extends Controller
{
    function index(Request $request)
    {
        return view('backend.reportclaimorders.index');
    }

    function indexData(Request $request)
    {

        DB::connection()->enableQueryLog();

        $user = Auth::user()->getRoleNames();

        $data = ClaimOrder::select(
            'claim_orders.id',
            DB::raw("DATE_FORMAT(claim_orders.updated_at, '%d/%m/%Y') AS order_date"),
            DB::raw("DATE_FORMAT(claim_orders.updated_at, '%H:%i:%s') AS order_time"),
            'claim_orders.claim_name',
            'claim_orders.description',
            'claim_orders.name_surename',
            'claim_orders.tel',
            'claim_orders.address',
            DB::raw("CONCAT(claim_orders.districts,' ', claim_orders.amphures,' ', claim_orders.provinces) AS districts"),
            'claim_orders.zipcode AS zip_code',
            'claim_orders.total_price'
        )
            ->orderBy('claim_orders.id', 'DESC');

        if ($user[0] != 'admin') {
            $data = $data->where('created_user_id', '=', Auth::user()->id);
        }

        if (!empty($request->from_date)) {
            $data = $data->whereBetween(DB::raw('DATE(orders.created_at)'), array($request->from_date, $request->to_date));
        }

        $data = $data->get();

        return datatables()->of($data)->make(true);
    }
}

resources/views/backend/working_days/create.blade.php
@extends('layouts.limitless.index')
@section('content')

<div class="row">
    <div class="col-md-6">
        @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        {!! Form::open(array('route' => 'working-days.store','method'=>'POST','class'=>'form-horizontal')) !!}

        <div class="panel panel-default">
            <div class="panel-heading">
                <h5 class="panel-title">สร้างวันทำการ<a class="heading-elements-toggle"><i class="icon-more"></i></a>
                </h5>
                <div class="heading-elements">
                    <a class="btn btn-primary" href="{{ route('working-days.index') }}"> Back</a>
                </div>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <label class="control-label col-lg-3">วันทำการวันที่:<span class="text-danger">*</span></label>
                    <div class="col-lg-9">
                        <input class="form-control" type="date" name="date_working" required='required'>
                    </div>
                </div>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Submit form <i
                            class="icon-arrow-right14 position-right"></i></button>
                </div>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
</div>
<script>
    $(document).ready(function(){
        // showProvinces();
        $.Thailand({
            $district: $('#district'), // input ของตำบล
            $amphoe: $('#amphoe'), // input ของอำเภอ
            $province: $('#province'), // input ของจังหวัด
            $zipcode: $('#zipcode'), // input ของรหัสไปรษณีย์
        });
    });
    /*function showProvinces(){
         $.ajax({
                type:'get',
                url:'{{ url('/') }}/api/province',
                success:function(resp){
                    $("#input_province").empty();
                    $("#input_province").append(
                        $('<option></option>')
                        .attr("value", "")
                        .html("กรุณาเลือกจังหวัด")
                    );
                    for(var i=0; i<resp.length; i++){
                    $("#input_province").append(
                        $('<option></option>')
                        .attr("value", ""+resp[i].id)
                        .html(""+resp[i].name_th)
                    );
                    }
                    showAmphoes();
                },error:function(){
                    alert("error");

                }
            });
    }*/

    /*function showAmphoes(){
        //INPUT
        var province_id = $("#input_province").val();
        if(province_id == ''){
            $("#input_amphoe").empty();
            $("#input_amphoe").append($('<option></option>').attr("value", "").html("กรุณาเลือกอำเภอ"));
            $("#input_district").empty();
            $("#input_district").append($('<option></option>').attr("value", "").html("กรุณาเลือกตำบล"));
            $("#zipcode").val('');
            return;
        }
        $.ajax({
            type:'get',
            url:"{{ url('/') }}/api/province/"+province_id+"/amphoe",
            success:function(resp){
                //console.log(resp);
                $("#input_amphoe").empty();
                $("#input_amphoe").append(
                        $('<option></option>')
                        .attr("value", "")
                        .html("กรุณาเลือกอำเภอ")
                    );
                for(var i=0; i<resp.length; i++){
                $("#input_amphoe").append(
                    $('<option></option>')
                    .attr("value", ""+resp[i].id)
                    .html(""+resp[i].name_th)
                );
                }
                showDistricts();
            },error:function(){
                alert("error");

            }
        });
    }*/

    /*function showDistricts(){

     //INPUT
     var amphoe_id = $("#input_amphoe").val();
        if(amphoe_id == ''){
            $("#input_district").empty();
            $("#input_district").append($('<option></option>').attr("value", "").html("กรุณาเลือกตำบล"));
            $("#zipcode").val('');
            return;
        }
        $.ajax({
            type:'get',
            url:"{{ url('/') }}/api/amphoe/"+amphoe_id+"/district",
            success:function(resp){
                //console.log(result);
                $("#input_district").empty();
                $("#input_district").append(
                        $('<option></option>')
                        .attr("value", "")
                        .html("กรุณาเลือกตำบล")
                    );
                for(var i=0; i<resp.length; i++){
                $("#input_district").append(
                    $('<option></option>')
                    .attr("value", ""+resp[i].id)
                    .attr("data-zipcode", ""+resp[i].zip_code)
                    .html(""+resp[i].name_th)
                );
                }
                showZipcode();
            },error:function(){
                alert("error");

            }
        });
    }*/

    /*function showZipcode(){
    //INPUT
    var zip_code = $("#input_district option:selected").attr('data-zipcode');
    $("#zipcode").val(zip_code);

    }*/

    function showProductAtttributes(){
         //INPUT
        var product_id = $("#product_id").val();
        if(product_id == ''){
            $("#products_attributes_id").empty();
            $("#products_attributes_id").append($('<option></option>').attr("value", "").html("เลือก"));
            return;
        }
        $.ajax({
            type:'get',
            url:"{{ url('/') }}/api/products_attributes/"+product_id,
            success:function(resp){
                //console.log(resp);
                $("#products_attributes_id").empty();
                $("#products_attributes_id").append(
                        $('<option></option>')
                        .attr("value", "")
                        .html("เลือก")
                    );
                for(var i=0; i<resp.length; i++){
                $("#products_attributes_id").append(
                    $('<option></option>')
                    .attr("value", ""+resp[i].id)
                    .html(""+resp[i].color)
                );
                }
            },error:function(){
                alert("error");

            }
        });
    }

</script>

@endsection

resources/views/backend/working_days/index.blade.php
@extends('layouts.limitless.index')
@section('content')
<div class="panel panel-default">
    <div class="panel-heading">
        <h5 class="panel-title">ระบบจัดการวันทำการ <a class="heading-elements-toggle"><i class="icon-more"></i></a>
        </h5>
        <div class="heading-elements">
        </div>
    </div>
    <div class="panel-body">
        @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <div class="table-responsive">
            <table class="table table-bordered table-xxs" id="test-datatable">
                <thead>
                    <tr class="bg-grey-600">
                        <th>ID</th>
                        <th>วันที่ทำการ</th>
                        <th>สถานะ เปิด-ปิด</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif
<script>
    $(function() {
         // Table setup
        // ------------------------------

        // Setting datatable defaults
        $.extend( $.fn.dataTable.defaults, {
            autoWidth: false,
            dom: '<"datatable-header"fBl><"datatable-scroll-wrap"t><"datatable-footer"ip>',
            language: {
                search: '<span>Filter:</span> _INPUT_',
                searchPlaceholder: 'Type to filter...',
                lengthMenu: '<span>Show:</span> _MENU_',
                paginate: { 'first': 'First', 'last': 'Last', 'next': '&rarr;', 'previous': '&larr;' }
            },
        });

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#test-datatable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ url('backend/working-days/data')}}",
        "columns": [
            {"data":'id'},
            {"data":'date_working'},
            {"data": null},
            {"data": null}
        ],
        buttons: [
            {
                text: 'สร้างวันทำการ',
                className: 'btn btn-success heading-btn',
                action: function(e, dt, node, config) {
                    location.href = "{{ route('working-days.create') }}";

                }
            }
        ],
        order: [[ 0, "desc" ]],
        columnDefs: [
                {className: "text-center", "targets": [0, 1,3 ]},
                {className: "text-left", "targets": [2]},
                {
                    "render": function (data, type, row, meta) {
                        dataReturn = '';
                        if(data.status_closed == 0){
                            dataReturn += '<span class="label label-success">เปิด</span>';
                        }else{
                            dataReturn += '<span class="label label-danger">ปิด</span>';
                        }

                        return dataReturn;
                    },
                    "targets": 2
                },
                {
                    "render": function (data, type, row, meta) {
                        dataReturn = '';
                        if(data.status_closed == 0){
                        dataReturn += '<a href="javascript:" onclick="confirmCloseWorkingDays('+ data.id +')" class="label bg-danger"><i class="icon-pencil7 position-left"></i>ปิดวันทำการ</a>&nbsp;';
                        }
                        return dataReturn;
                    },
                    "targets": 3
                },
            ],
    });

    });

    function confirmCloseWorkingDays(id) {
            swal({
                title: "ยืนยันการปิดวันทำการ",
                // text: "Are you sure you want to delete this Senders?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, ยืนยันการปิด!",
                cancelButtonText: "ยกเลิก",
                closeOnConfirm: false
            }, function (isConfirm) {
                if (!isConfirm) return;
                $.ajax({
                    url : "{{ url('backend/working-days')}}" + '/' + id,
                    type : "POST",
                    data : {'_method' : 'PATCH'},
                    success: function () {
                        swal({title: "Success", text: "วันทำการของคุณได้ปิดเรียบร้อย! \nคลิกปุ่ม 'Ok' เพื่อรีเฟรชหน้า.", type: "success"},
                            function(){
                                location.reload();
                            }
                        );
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        swal("Error!", "Please try again", "error");
                    }
                });
            });
    }
</script>

@endsection